config/routes.rb
Rails.application.routes.draw do
  get 'post/dashboard'
  get 'pages/index'
  get 'post/create'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :image_url, :content, presence: true

    before_save :replace_word

    def replace_word
        self.content = self.content.gsub "spoiler", ""
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
  def dashboard
  end

  def create
    @post = Post.create(title: params[:title], image_url: params[:image_url], content: params[:content])

    #if @post.save == false
    #  redirect_to root_path
    #end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Juegos de The Legend of Zelda</h1>

<%= link_to "Dashboard", post_dashboard_path%>

<% @posts.each do |post| %>
    <ul>
        <li><%=post.title%></li>
        <li><%=post.created_at%></li>
        <li><%=image_tag post.image_url%></li>
        <li><%=post.content%></li>
    </ul>
<%end%>

app/views/post/create.html.erb
<% if @post.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %><br> No se ha podido enviar el post:</h2>

        <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>    
        </ul>
    </div>

<% else %>

<h1> Tu juego se ha guardado con éxito </h1>
<% end %>

app/views/post/dashboard.html.erb
<h1>Ingresa aquí un nuevo juego de Zelda</h1>

    <form id="create_post" method="get" action="<%= post_create_path%>">

            <div class="mb-3">
                <label for="form_title" class="form-label">Título</label>
                <input name="title" class="form-control">
            </div>

            <div class="mb-3">
                <label for="form_image_url" class="form-label">Imagen</label>
                <input name="image_url" class="form-control">
            </div>

            <div class="mb-3">
                <label for="form_content" class="form-label">Descripción</label>
                <input name= "content" class="form-control" type="textarea">
            </div>

        <input class="btn btn-primary" type="submit" value="Enviar">

    </form>
<br>
<%= link_to "Volver a Index", pages_index_path%>